function EEG = pop_constant_data( EEG, interpWin )

if isempty(interpWin)
    interpWin = [-2, 400];
end

%Check EEG structure for tmscut fields generated by tesa_removedata.m 
if ~isfield(EEG,'tmscut');
    error('Artifact data not removed. Please run pop_tesa_removedata first.');
end

%Check that tmscut fields generated by tesa_removedata.m contain data
if isfield(EEG,'tmscut');
    if isempty(EEG.tmscut(1).tmscut1) || isempty(EEG.tmscut(1).tmscut2);
        error('Artifact removal time points do not contain data. Please re-run pop_tesa_removedata.');
    end
end

for z = 1:size(EEG.tmscut,2)       
    if strcmp(EEG.tmscut(z).interpolated,'no')
        interpData = [];

        %Checks whether data sampling rate has changed
        tp1 = []; tp2 = [];
        if isequal(EEG.srate, EEG.tmscut(z).srate)
            tp1 = EEG.tmscut(z).tmscut1;
            tp2 = EEG.tmscut(z).tmscut2;
        elseif ~isequal(EEG.srate, EEG.tmscut(z).srate)
            [val1, tp1] = min(abs(EEG.times-EEG.tmscut(z).cutTimesTMS(1,1)));
            [val2, tp2] = min(abs(EEG.times-EEG.tmscut(z).cutTimesTMS(1,2)));
        end

        %fit linear function to data
        for a = 1:size(EEG.data, 1)
            for b = 1:size(EEG.data, 3)

                %Extract time points before and after removed data
                x(1,1) = EEG.times(1, tp1-1);
                x(1,2) = EEG.times(1, tp2+1);

                %Extract data points before and after removed data
                y(1,1) = EEG.data(a, tp1-1, b);
                y(1,2) = EEG.data(a, tp1-1, b);

                %Interpolate missing data points
                X = EEG.times(1, tp1:tp2); %missing time points
                interpData(a, :, b) = ones([1 size(X, 2)]) * EEG.data(a, tp1-1, b);
            end
        end

        %Insert interpolated data 
        % interpData = repmat(interpData, [1, floor(size(EEG.data(:, tp1:tp2, :), 2)/2), 1]);
        EEG.data(:, tp1:tp2, :) = interpData;

        %display message
        fprintf('Linear interpolation between %d ms and %d ms \n', EEG.tmscut(z).cutTimesTMS(1,1), EEG.tmscut(z).cutTimesTMS(1,2));

        %Indicate that interpolation has happened
        EEG.tmscut(z).interpolated = 'yes';
    end
end
    
end